---
# ----------------------------------------------------------------------------------- #
# VCF Identity Broker Configuration
# ----------------------------------------------------------------------------------- #
# Description:
#   This file contains the instance-level configuration for the VMware Cloud
#   Foundation instance.
#
# Required Configuration:
#   - identity_broker.hostname: FQDN for the VCF Identity Broker.
# ----------------------------------------------------------------------------------- #

identity_broker:
  hostname: vidblb-dc1-az1.corp.internal