---
# Copyright (c) Broadcom. All Rights Reserved.
# The term "Broadcom" refers solely to the Broadcom Inc. corporate affiliate that
# distributes this software.
#
# You are hereby granted a non-exclusive, worldwide, royalty-free license under
# Broadcom's copyrights to use, copy, modify, and distribute this software in source
# code or binary form for use in connection with Broadcom products.
#
# This copyright notice shall be included in all copies or substantial portions of the
# software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
# CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
# OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
# ----------------------------------------------------------------------------------- #
# Role: vcf_installer.trusted_certificate
# ----------------------------------------------------------------------------------- #
# Description:
#   This role is responsible for adding a trusted certificate to the VCF Installer
#   trust store.
# ----------------------------------------------------------------------------------- #
# Variables:
#   Required:
#   - trusted_certificate            : The certificate in PEM format.
#   Optional:
#   - trusted_certificate_usage_type : The certificate usage type.
# ----------------------------------------------------------------------------------- #

- name: Validate Trusted Certificate Variable
  ansible.builtin.assert:
    that:
      - trusted_certificate is defined
      - trusted_certificate | length > 0
    fail_msg: "trusted_certificate must be defined and contain a valid PEM certificate."

- name: Add Trusted Certificate
  broadcom.vcf.vcf_installer_trusted_certificate:
    vcf_installer_hostname: "{{ all_iac_vars.vcf_installer.hostname }}"
    vcf_installer_user: "{{ all_iac_vars.vcf_installer.username | default('admin@local') }}"
    vcf_installer_password: "{{ vcf_installer_password | default(all_iac_vars.vcf_installer.password) }}"
    certificate: "{{ trusted_certificate }}"
    certificate_usage_type: "{{ trusted_certificate_usage_type | default('TRUSTED_FOR_OUTBOUND') }}"
  register: trusted_certificate_result
