---
# Copyright (c) Broadcom. All Rights Reserved.
# The term "Broadcom" refers solely to the Broadcom Inc. corporate affiliate that
# distributes this software.
#
# You are hereby granted a non-exclusive, worldwide, royalty-free license under
# Broadcom's copyrights to use, copy, modify, and distribute this software in source
# code or binary form for use in connection with Broadcom products.
#
# This copyright notice shall be included in all copies or substantial portions of the
# software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
# CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
# OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
# ----------------------------------------------------------------------------------- #
# Role: vcf_installer.appliance
# Task: Dispatch to VCF Installer Appliance Tasks
# ----------------------------------------------------------------------------------- #
# Description:
#   Dispatches to the appropriate task file based on the state of the VCF Installer
#   appliance.
# ----------------------------------------------------------------------------------- #

- name: Validate VCF Installer Appliance Deployment Location
  ansible.builtin.include_tasks: validate.yml
  when: appliance_state | default('present') | lower == 'validate'

- name: Ensure VCF Installer Appliance is Present
  ansible.builtin.include_tasks: present.yml
  when: appliance_state | default('present') | lower == 'present'

- name: Ensure VCF Installer is Absent
  ansible.builtin.include_tasks: absent.yml
  when: appliance_state | default('present') | lower == 'absent'
