---
# ----------------------------------------------------------------------------------- #
# VCF Automation Configuration
# ----------------------------------------------------------------------------------- #
# Description:
#   This file contains the instance-level configuration for the VMware Cloud
#   Foundation instance.
# ----------------------------------------------------------------------------------- #

automation:
  hostname: flt-auto01.rainpole.io
  admin_password: "{{ vault_automation_admin_password }}"
  services_runtime_hostname: flt-vcfa-sr01.rainpole.io
  node_ips:
    - 10.11.10.46
    - 10.11.10.47
    - 10.11.10.48
    - 10.11.10.49
    - 10.11.10.50
  node_prefix: sfo-m01-node-01
  internal_cluster_cidr: 198.18.0.0/15
