---
# ----------------------------------------------------------------------------------- #
# Lifecycle Management Configuration
# ----------------------------------------------------------------------------------- #
# Description:
#   This file contains the instance-level configuration for the VMware Cloud
#   Foundation instance.
#
# Required Configuration:
#   - lcm.sddc.hostname:  FQDN for the SDDC lifecycle management.
#   - lcm.fleet.hostname: FQDN for the fleet lifecycle management.
# ----------------------------------------------------------------------------------- #

lcm:
  sddc:
    hostname: sfo-ic01.sfo.rainpole.io
  fleet:
    hostname: flt-fc01.rainpole.io