---
# ----------------------------------------------------------------------------------- #
# Default NSX Configuration
# ----------------------------------------------------------------------------------- #
# Description:
#   This file contains the instance-level configuration for the VMware Cloud
#   Foundation instance.
# ----------------------------------------------------------------------------------- #

nsx:
  deployment:
    root_password: "{{ vault_nsx_root_password }}"
    admin_password: "{{ vault_nsx_admin_password }}"
    audit_password: "{{ vault_nsx_audit_password }}"