---
# ----------------------------------------------------------------------------------- #
# SDDC Manager Configuration
# ----------------------------------------------------------------------------------- #
# Description:
#   This file contains the instance-level configuration for the VMware Cloud
#   Foundation instance.
# ----------------------------------------------------------------------------------- #

sddc_manager:
  hostname: sfo-vcf01.sfo.rainpole.io
  root_password: "{{ vault_sddc_manager_root_password }}"
  vcf_password: "{{ vault_sddc_manager_vcf_password }}"
  admin_password: "{{ vault_sddc_manager_admin_password }}"
