---
# Copyright (c) Broadcom. All Rights Reserved.
# The term "Broadcom" refers solely to the Broadcom Inc. corporate affiliate that
# distributes this software.
#
# You are hereby granted a non-exclusive, worldwide, royalty-free license under
# Broadcom's copyrights to use, copy, modify, and distribute this software in source
# code or binary form for use in connection with Broadcom products.
#
# This copyright notice shall be included in all copies or substantial portions of the
# software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
# CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
# OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
# ----------------------------------------------------------------------------------- #
# Role: iac.get_settings
# ----------------------------------------------------------------------------------- #
# Description:
#   This role is responsible for loading the settings for the IaC.
# ----------------------------------------------------------------------------------- #

- name: Load Settings from Local
  ansible.builtin.include_role:
    name: broadcom.vcf.iac.load_base_iac
  vars:
    working_dir: "{{ playbook_dir }}/../infra-as-code/"
  when: iac_git_url is not defined
- name: Load Settings from Git Repository
  block:
    - name: Set the Display Name for the Git Repository
      ansible.builtin.set_fact:
        git_display: >-
          {% if 'ssh' in iac_git_url | lower %}{{ iac_git_url }}{% else %}git https address{% endif %}
    - name: Checkout IaC from Git Repository {{ git_display }}
      ansible.builtin.git:
        repo: "{{ iac_git_url }}"
        dest: "{{ ansible_facts['env']['HOME'] }}/{{ iac_git_clone_folder }}"
        version: "{{ iac_git_branch }}"
        accept_hostkey: True
      environment:
          GIT_SSL_NO_VERIFY: "true"
      register: git_ret
    - name: Load Settings from IaC
      ansible.builtin.include_role:
        name: broadcom.vcf.iac.load_base_iac
      vars:
        working_dir: "{{ ansible_facts['env']['HOME'] }}/{{ iac_git_clone_folder }}/{{ iac_folder }}/"
  when: iac_git_url is defined
