---
# Copyright (c) Broadcom. All Rights Reserved.
# The term "Broadcom" refers solely to the Broadcom Inc. corporate affiliate that
# distributes this software.
#
# You are hereby granted a non-exclusive, worldwide, royalty-free license under
# Broadcom's copyrights to use, copy, modify, and distribute this software in source
# code or binary form for use in connection with Broadcom products.
#
# This copyright notice shall be included in all copies or substantial portions of the
# software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
# CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
# OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
# ----------------------------------------------------------------------------------- #
# Role: sddc_manager.dns
# ----------------------------------------------------------------------------------- #
# Description:
#   This role is responsible for updating DNS configuration in a
#   VMware Cloud Foundation instance.
# ----------------------------------------------------------------------------------- #

- name: Find DNS in IaC Configuration
  set_fact:
    dns_config:
      dnsServers: "{{ (dns_config.dnsServers | default([])) + [ {'ipAddress': item, 'isPrimary': (ansible_loop.index0 == 0)} ] }}"
  loop: "{{ all_iac_vars.dns.servers }}"
  loop_control:
    extended: yes

- name: Fail if DNS Not Found
  ansible.builtin.fail:
    msg: "DNS is not found in IaC configuration"
  when: dns_config is none

- name: Validate DNS Configuration
  ansible.builtin.include_tasks: validate_dns_config.yml

- name: Update DNS Configuration
  ansible.builtin.include_tasks: update_dns_config.yml
