---
# Copyright (c) Broadcom. All Rights Reserved.
# The term "Broadcom" refers solely to the Broadcom Inc. corporate affiliate that
# distributes this software.
#
# You are hereby granted a non-exclusive, worldwide, royalty-free license under
# Broadcom's copyrights to use, copy, modify, and distribute this software in source
# code or binary form for use in connection with Broadcom products.
#
# This copyright notice shall be included in all copies or substantial portions of the
# software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
# CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
# OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
# ----------------------------------------------------------------------------------- #
# Role: sddc_manager.dns
# Task: Update DNS Configuration
# ----------------------------------------------------------------------------------- #
# Description:
# This task updates DNS configuration in a VMware Cloud Foundation instance.
# ----------------------------------------------------------------------------------- #

- name: Update DNS Configuration
  broadcom.vcf.sddc_manager_dns:
    sddc_manager_hostname: "{{ all_iac_vars.sddc_manager.hostname }}"
    sddc_manager_user: "{{ all_iac_vars.vsphere.vcenter.sso.username }}"
    sddc_manager_password: "{{ vcenter_administrator_password | default(all_iac_vars.vsphere.vcenter.sso.password) }}"
    dns_config: "{{ dns_config }}"
    state: "{{ dns_state }}"
  register: dns_result

- name: Fail if Task Returned Errors
  ansible.builtin.fail:
    msg: "Failed to update DNS. Errors: {{ dns_result.meta.errors | default([]) | to_nice_yaml }}"
  when:
    - not ansible_check_mode
    - dns_result.meta is defined
    - dns_result.meta.errors is defined
    - dns_result.meta.errors | length > 0

- name: Display Status Message
  ansible.builtin.debug:
    msg: "DNS configuration update to {{ dns_state | upper }} completed with status: {{ dns_result.msg }}."
  when:
    - not ansible_check_mode
    - dns_result is defined
